
#ifdef __cplusplus
extern "C" {
#endif

#pragma once


#include "hocct-ModelingAlgorithmsType.h"

#include "HOCCT_ModelingAlgorithms_BRepBuilderAPI_MakeShape.h"

#include "HOCCT_ModelingAlgorithms_BRepBuilderAPI_Command.h"


#define BREPOFFSETAPI_MAKEOFFSETSHAPE_DECL_VIRT(Type) \



#define BREPOFFSETAPI_MAKEOFFSETSHAPE_DECL_NONVIRT(Type) \



#define BREPOFFSETAPI_MAKEOFFSETSHAPE_DECL_ACCESSOR(Type) \



#define BREPOFFSETAPI_MAKEOFFSETSHAPE_DEF_VIRT(Type) \



#define BREPOFFSETAPI_MAKEOFFSETSHAPE_DEF_NONVIRT(Type) \



#define BREPOFFSETAPI_MAKEOFFSETSHAPE_DEF_ACCESSOR(Type) \



BREPBUILDERAPI_MAKESHAPE_DECL_VIRT(BRepOffsetAPI_MakeOffsetShape)
BREPBUILDERAPI_COMMAND_DECL_VIRT(BRepOffsetAPI_MakeOffsetShape)
BREPOFFSETAPI_MAKEOFFSETSHAPE_DECL_VIRT(BRepOffsetAPI_MakeOffsetShape)
BREPOFFSETAPI_MAKEOFFSETSHAPE_DECL_NONVIRT(BRepOffsetAPI_MakeOffsetShape)
BREPOFFSETAPI_MAKEOFFSETSHAPE_DECL_ACCESSOR(BRepOffsetAPI_MakeOffsetShape)

#ifdef __cplusplus
}
#endif

